spring:
  application:
    name: test_kuber
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5435/test_kuber_local
    username: test_kuber_local
    password: password
    driver-class-name: org.postgresql.Driver
server:
  port: 8081