apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  DB_USER: cG9zdGdyZXNfcHJvZA==     # base64 от "postgres_prod"
  DB_PASSWORD: cGFzc3dvcmRfcHJvZA== # base64 от "password_prod"