{{- if and .Values.ingress.enabled (index .Values.nginxIngress.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "spring-app.fullname" . }}-ingress
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /(.*)
            pathType: {{ .Values.ingress.pathType }}
            backend:
              service:
                name: {{ include "spring-app.fullname" . }}-service
                port:
                  number: {{ .Values.service.port }}
{{- end }}