apiVersion: v1
kind: Secret
metadata:
  name: {{ include "spring-app.fullname" . }}
  labels:
    {{- include "spring-app.labels" . | nindent 4 }}
type: Opaque
data:
  DB_USER: {{ .Values.db.user | b64enc }}               # ← ВАЖНО: название DB_USER должно быть ТОЧНО таким, как в application.yaml приложения
  DB_PASSWORD: {{ .Values.db.password | b64enc }}       # ← ВАЖНО: название DB_PASSWORD должно быть ТОЧНО таким, как в application.yaml приложения